/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9027fae7-26cb-4603-ab33-d532c9842dff",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_CIfeGEUWy",
    "aws_user_pools_web_client_id": "1f8taqv08q90lj2rk9gdi6nces",
    "oauth": {}
};


export default awsmobile;
